[[pages]]
path = "_pages/home_page.py"
name = "Home"
icon = "ğŸ¡"


[[pages]]
path = "_pages/orders.py"
name = "Orders"
icon = "ğŸ§¾"


[[pages]]
path = "_pages/sales.py"
name = "Revenues"
icon = "ğŸ’µ"
