[[pages]]
path = "_pages/home_page.py"
name = "Home"
icon = "ğŸ¡"


[[pages]]
path = "_pages/orders.py"
name = "Orders Uncovered"
icon = "ğŸ§¾"


[[pages]]
path = "_pages/sales.py"
name = "Revenue Insights"
icon = "ğŸ’µ"

[[pages]]
path = "_pages/social_media.py"
name = "Social Media Boost"
icon = "ğŸ“¸"